version: "3.9"

networks:
  rag-misw:
    driver: bridge

services:
  backend:
    build:
      context: ./202515-MISW4411-Backend-Grupo20
    image: misw4411-backend:latest
    env_file:
      - ./202515-MISW4411-Backend-Grupo20/.env
    environment:
      - UVICORN_WORKERS=2
      - GIT_PYTHON_REFRESH=quiet
    expose:
      - "8000"
    networks:
      - rag-misw
    restart: unless-stopped

  frontend:
    build:
      context: ./MISW4411-Frontend-Template
    image: misw4411-frontend:latest
    expose:
      - "3000"
    networks:
      - rag-misw
    depends_on:
      - backend
    restart: unless-stopped

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    networks:
      - rag-misw
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/default-gpt.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
