networks:
  rag-misw:
    driver: bridge

services:
  backend:
    build:
      context: ./MISW4411-Backend
    image: misw4411-backend-img
    ports:
      - "8000:8000"
    networks:
      - rag-misw
    restart: unless-stopped

  frontend:
    build:
      context: ./MISW4411-Frontend-Template
    image: misw4411-frontend-img
    ports:
      - "3000:3000"
    networks:
      - rag-misw
    depends_on:
      - backend
    restart: unless-stopped

  proxy:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    networks:
      - rag-misw
    depends_on:
      - frontend
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
